name: PHP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, bcmath, pdo, pdo_mysql, zip
        coverage: 'none'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: ./vendor/bin/pest
      continue-on-error: true

    - name: Send email on failure
      if: failure()
      run: |
        echo "Sending email on failure..."
        echo "Build failed for commit ${GITHUB_SHA}" | mail -s "Build Failed" tongsreng@itc.edu.kh
        git log -1 --pretty=format:"%an" | xargs -I {} echo "Notifying committer {}"
        git show --quiet --pretty=format:%B ${GITHUB_SHA} | mail -s "Build Failure Details" $(git log -1 --pretty=format:"%an" ${GITHUB_SHA})
