name: Laravel Tests

on:
  push:
    branches:
      - master  # Adjust branch name as per your repository's main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install 

      # Run Laravel Artisan tests
      - name: Run Tests
        run: php artisan test

      # Notify on failure
      - name: Notify on failure
        if: failure()
        run: |
          echo "Build failed, sending notification..."
          echo "Build failed on branch $GITHUB_REF" | mail -s "Build Failed" tongsreng@itc.edu.kh

          COMMITTER_EMAIL=$(git log -1 --format='%ae')
          if [ -n "$COMMITTER_EMAIL" ]; then
            echo "Build failed, notifying commit author..."
            echo "Build failed on branch $GITHUB_REF" | mail -s "Build Failed" "$COMMITTER_EMAIL"
          fi
